---
title: "COMPSCIX 415.2 Homework 1"
author: "Pankaj Mittal"
date: "June 7, 2018"
output:
  html_document: default
  pdf_document: default
---

My Github repository for my assignments can be found at this URL: https://github.com/pankajmit/compscix-415-2-assignments.git

```{r warning=FALSE, message=FALSE}
library(mdsr)
data("WorldCities")

```

## Question 1

This dataset has 23,018 observations for 10 variables.
Some of the variable names are - code, name, latitude, langitude etc.

## Question 2

```{r}
glimpse(WorldCities)
WorldCities <- head(WorldCities, 200)
country_col <- WorldCities$country
unique(country_col)

region_col <- WorldCities$region
unique(region_col)

```

## Question 3
```{r}
WorldCities %>% select(country) %>% unique
```


```{r}
WorldCities %>% ggplot(aes(x = population)) +
geom_histogram() +
  xlab('City Population')
```

## Question 4

```{r}
WorldCities %>% ggplot(aes(x = population)) +
geom_histogram() +
  xlab('Population of World Cities') +
  ylab('Count of Cities') +
  ggtitle('Answer to Question 4') +
  theme_bw()

```

